# NumPy-100 前50题

- 来源：rougier/numpy-100
- 完成范围：第1～50题
- 环境：Python 3.10 + NumPy

In [1]:
import numpy as np

print("NumPy已成功导入")

NumPy已成功导入


In [2]:
print("NumPy版本：")
print(np.__version__)

print("\nNumPy配置信息：")
np.show_config()

NumPy版本：
2.2.6

NumPy配置信息：
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7xf_vzet/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7xf_vzet/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.29  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: C:/a/numpy/numpy/.openblas
    version: 0.3.29
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7xf_vzet/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-7xf_vzet/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configu

In [3]:
z = np.zeros(10)

print(z)
print("形状：", z.shape)
print("类型：", z.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
形状： (10,)
类型： float64


In [4]:
z = np.zeros(10)

memory_by_formula = (
    z.size * z.itemsize
)

print("元素数量：", z.size)
print("每个元素字节数：", z.itemsize)
print("总字节数：", memory_by_formula)
print("使用nbytes检查：", z.nbytes)

元素数量： 10
每个元素字节数： 8
总字节数： 80
使用nbytes检查： 80


In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [6]:
z = np.zeros(
    10,
    dtype=np.int32
)

z[4] = 1

print(z)

[0 0 0 0 1 0 0 0 0 0]


In [7]:
z = np.arange(
    10,
    50
)

print(z)
print("元素数量：", z.size)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
元素数量： 40


In [8]:
z = np.arange(10)

reversed_z = z[::-1]

print("原向量：")
print(z)

print("\n反转后：")
print(reversed_z)

原向量：
[0 1 2 3 4 5 6 7 8 9]

反转后：
[9 8 7 6 5 4 3 2 1 0]


In [9]:
z = np.arange(9).reshape(
    3,
    3
)

print(z)
print("形状：", z.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
形状： (3, 3)


In [10]:
values = np.array([
    1, 2, 0, 0, 4, 0
])

indices = np.nonzero(values)[0]

print("原数组：")
print(values)

print("\n非零元素的索引：")
print(indices)

print("\n对应的非零元素：")
print(values[indices])

原数组：
[1 2 0 0 4 0]

非零元素的索引：
[0 1 4]

对应的非零元素：
[1 2 4]


In [11]:
z = np.eye(3)

print("3×3单位矩阵：")
print(z)

print("\n数据类型：", z.dtype)
print("形状：", z.shape)

3×3单位矩阵：
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

数据类型： float64
形状： (3, 3)


In [12]:
rng = np.random.default_rng(seed=42)

z = rng.random((3, 3, 3))

print("随机数组：")
print(z)

print("\n数组形状：", z.shape)
print("元素数量：", z.size)


随机数组：
[[[0.77395605 0.43887844 0.85859792]
  [0.69736803 0.09417735 0.97562235]
  [0.7611397  0.78606431 0.12811363]]

 [[0.45038594 0.37079802 0.92676499]
  [0.64386512 0.82276161 0.4434142 ]
  [0.22723872 0.55458479 0.06381726]]

 [[0.82763117 0.6316644  0.75808774]
  [0.35452597 0.97069802 0.89312112]
  [0.7783835  0.19463871 0.466721  ]]]

数组形状： (3, 3, 3)
元素数量： 27


In [13]:
rng = np.random.default_rng(seed=42)

z = rng.random((10, 10))

print("随机矩阵：")
print(z)

print("\n最小值：", z.min())
print("最大值：", z.max())

随机矩阵：
[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
  0.7611397  0.78606431 0.12811363 0.45038594]
 [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142  0.22723872
  0.55458479 0.06381726 0.82763117 0.6316644 ]
 [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835  0.19463871
  0.466721   0.04380377 0.15428949 0.68304895]
 [0.74476216 0.96750973 0.32582536 0.37045971 0.46955581 0.18947136
  0.12992151 0.47570493 0.22690935 0.66981399]
 [0.43715192 0.8326782  0.7002651  0.31236664 0.8322598  0.80476436
  0.38747838 0.2883281  0.6824955  0.13975248]
 [0.1999082  0.00736227 0.78692438 0.66485086 0.70516538 0.78072903
  0.45891578 0.5687412  0.139797   0.11453007]
 [0.66840296 0.47109621 0.56523611 0.76499886 0.63471832 0.5535794
  0.55920716 0.3039501  0.03081783 0.43671739]
 [0.21458467 0.40852864 0.85340307 0.23393949 0.05830274 0.28138389
  0.29359376 0.66191651 0.55703215 0.78389821]
 [0.66431354 0.40638686 0.81402038 0.16697292 0.02271207 0.09004786
  0.722

In [14]:
rng = np.random.default_rng(seed=42)

z = rng.random(30)

mean_value = z.mean()

print("随机向量：")
print(z)

print("\n元素数量：", z.size)
print("平均值：", mean_value)

随机向量：
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
 0.7611397  0.78606431 0.12811363 0.45038594 0.37079802 0.92676499
 0.64386512 0.82276161 0.4434142  0.22723872 0.55458479 0.06381726
 0.82763117 0.6316644  0.75808774 0.35452597 0.97069802 0.89312112
 0.7783835  0.19463871 0.466721   0.04380377 0.15428949 0.68304895]

元素数量： 30
平均值： 0.5591387423201123


In [15]:
z = np.ones(
    (10, 10),
    dtype=np.int32
)

z[1:-1, 1:-1] = 0

print(z)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [16]:
original = np.ones(
    (5, 5),
    dtype=np.int32
)

bordered = np.pad(
    original,
    pad_width=1,
    mode="constant",
    constant_values=0
)

print("原数组：")
print(original)

print("\n添加边界后的数组：")
print(bordered)

print("\n原形状：", original.shape)
print("新形状：", bordered.shape)

原数组：
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

添加边界后的数组：
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]

原形状： (5, 5)
新形状： (7, 7)


In [17]:
print("0 * np.nan：", 0 * np.nan)
print("np.nan == np.nan：", np.nan == np.nan)
print("np.inf > np.nan：", np.inf > np.nan)
print("np.nan - np.nan：", np.nan - np.nan)
print("np.nan in set([np.nan])：", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1：", 0.3 == 3 * 0.1)

0 * np.nan： nan
np.nan == np.nan： False
np.inf > np.nan： False
np.nan - np.nan： nan
np.nan in set([np.nan])： True
0.3 == 3 * 0.1： False


In [18]:
values = np.arange(1, 5)

z = np.diag(
    values,
    k=-1
)

print("用于构造对角线的数值：")
print(values)

print("\n生成的矩阵：")
print(z)

print("\n矩阵形状：", z.shape)

用于构造对角线的数值：
[1 2 3 4]

生成的矩阵：
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

矩阵形状： (5, 5)


In [19]:
z = np.zeros(
    (8, 8),
    dtype=np.int32
)

z[1::2, ::2] = 1
z[::2, 1::2] = 1

print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
shape = (6, 7, 8)

flat_index = 99

coordinate = np.unravel_index(
    flat_index,
    shape
)

print("数组形状：", shape)
print("第100个元素的一维索引：", flat_index)
print("对应的三维索引：", coordinate)

数组形状： (6, 7, 8)
第100个元素的一维索引： 99
对应的三维索引： (np.int64(1), np.int64(5), np.int64(3))


In [21]:
pattern = np.array([
    [0, 1],
    [1, 0]
])

z = np.tile(
    pattern,
    (4, 4)
)

print(z)
print("形状：", z.shape)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
形状： (8, 8)


In [22]:
rng = np.random.default_rng(seed=42)

z = rng.random((5, 5)) * 100

minimum = z.min()
maximum = z.max()

normalized = (
    (z - minimum)
    / (maximum - minimum)
)

print("原矩阵：")
print(z)

print("\n归一化后的矩阵：")
print(normalized)

print("\n归一化后的最小值：", normalized.min())
print("归一化后的最大值：", normalized.max())

原矩阵：
[[77.39560486 43.88784398 85.85979199 69.73680291  9.41773479]
 [97.56223516 76.1139702  78.60643053 12.81136327 45.03859379]
 [37.07980242 92.67649888 64.38651201 82.27616133 44.34141988]
 [22.72387218 55.4584787   6.38172561 82.7631172  63.16643991]
 [75.80877401 35.45259681 97.06980244 89.31211213 77.83834971]]

归一化后的矩阵：
[[0.7788274  0.41133921 0.87165631 0.69483136 0.03329669]
 [1.         0.76477139 0.79210684 0.07051548 0.42395977]
 [0.33667367 0.94641688 0.63615335 0.83235371 0.41631369]
 [0.17922851 0.53823732 0.         0.83769428 0.6227725 ]
 [0.76142422 0.31882769 0.99459936 0.90951879 0.7836831 ]]

归一化后的最小值： 0.0
归一化后的最大值： 1.0


In [23]:
rgba_dtype = np.dtype([
    ("r", np.uint8),
    ("g", np.uint8),
    ("b", np.uint8),
    ("a", np.uint8)
])

print("RGBA数据类型：")
print(rgba_dtype)

print("每种颜色占用字节数：", rgba_dtype.itemsize)

RGBA数据类型：
[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
每种颜色占用字节数： 4


In [24]:
colors = np.zeros(
    3,
    dtype=rgba_dtype
)

colors[0] = (255, 0, 0, 255)
colors[1] = (0, 255, 0, 255)
colors[2] = (0, 0, 255, 128)

print(colors)
print("第一个颜色的红色通道：", colors[0]["r"])

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 128)]
第一个颜色的红色通道： 255


In [25]:
a = np.ones(
    (5, 3),
    dtype=np.int32
)

b = np.ones(
    (3, 2),
    dtype=np.int32
)

result = a @ b

print("矩阵A：")
print(a)

print("\n矩阵B：")
print(b)

print("\n矩阵乘法结果：")
print(result)

print("\n结果形状：", result.shape)

矩阵A：
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

矩阵B：
[[1 1]
 [1 1]
 [1 1]]

矩阵乘法结果：
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]

结果形状： (5, 2)


In [26]:
z = np.arange(11)

mask = (z > 3) & (z < 8)

print("原数组：")
print(z)

print("\n布尔条件：")
print(mask)

z[mask] *= -1

print("\n修改后的数组：")
print(z)

原数组：
[ 0  1  2  3  4  5  6  7  8  9 10]

布尔条件：
[False False False False  True  True  True  True False False False]

修改后的数组：
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [27]:
values = np.array([
    1.0,
    0.0
])

with np.errstate(all="ignore"):
    result = values / 0

print(result)

[inf nan]


In [28]:
z = np.zeros(
    (5, 5),
    dtype=np.int32
)

z += np.arange(5)

print(z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [29]:
z = np.linspace(
    0,
    1,
    11,
    endpoint=False
)[1:]

print(z)
print("元素数量：", z.size)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
元素数量： 10


In [30]:
rng = np.random.default_rng(
    seed=42
)

z = rng.random(10)

print("排序前：")
print(z)

z.sort()

print("\n排序后：")
print(z)

排序前：
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
 0.7611397  0.78606431 0.12811363 0.45038594]

排序后：
[0.09417735 0.12811363 0.43887844 0.45038594 0.69736803 0.7611397
 0.77395605 0.78606431 0.85859792 0.97562235]


In [31]:
rng = np.random.default_rng(
    seed=42
)

z = rng.random(10)

maximum_index = z.argmax()
maximum_value = z[maximum_index]

print("原数组：")
print(z)

print("\n最大值：", maximum_value)
print("最大值索引：", maximum_index)

z[maximum_index] = 0

print("\n修改后的数组：")
print(z)

原数组：
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
 0.7611397  0.78606431 0.12811363 0.45038594]

最大值： 0.9756223516367559
最大值索引： 5

修改后的数组：
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.
 0.7611397  0.78606431 0.12811363 0.45038594]


In [32]:
coordinate_dtype = np.dtype([
    ("x", np.float32),
    ("y", np.float32)
])

grid = np.zeros(
    (5, 5),
    dtype=coordinate_dtype
)

values = np.linspace(
    0,
    1,
    5
)

x_grid, y_grid = np.meshgrid(
    values,
    values
)

grid["x"] = x_grid
grid["y"] = y_grid

print(grid)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [33]:
integer_types = [
    np.uint8,
    np.uint16,
    np.int8,
    np.int32,
    np.int64
]

for dtype in integer_types:
    info = np.iinfo(dtype)

    print(
        np.dtype(dtype).name,
        "最小值：",
        info.min,
        "最大值：",
        info.max
    )

uint8 最小值： 0 最大值： 255
uint16 最小值： 0 最大值： 65535
int8 最小值： -128 最大值： 127
int32 最小值： -2147483648 最大值： 2147483647
int64 最小值： -9223372036854775808 最大值： 9223372036854775807


In [34]:
float_types = [
    np.float32,
    np.float64
]

for dtype in float_types:
    info = np.finfo(dtype)

    print("\n类型：", np.dtype(dtype).name)
    print("最小有限值：", info.min)
    print("最大有限值：", info.max)
    print("机器精度eps：", info.eps)
    print("最小正规正数tiny：", info.tiny)


类型： float32
最小有限值： -3.4028235e+38
最大有限值： 3.4028235e+38
机器精度eps： 1.1920929e-07
最小正规正数tiny： 1.1754944e-38

类型： float64
最小有限值： -1.7976931348623157e+308
最大有限值： 1.7976931348623157e+308
机器精度eps： 2.220446049250313e-16
最小正规正数tiny： 2.2250738585072014e-308


In [35]:
z = np.zeros(
    (40, 40)
)

with np.printoptions(
    threshold=np.inf
):
    print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
z = np.arange(100)

target = 36.7

distances = np.abs(
    z - target
)

closest_index = distances.argmin()
closest_value = z[closest_index]

print("目标值：", target)
print("距离数组：")
print(distances)

print("\n最近值索引：", closest_index)
print("最近值：", closest_value)

目标值： 36.7
距离数组：
[36.7 35.7 34.7 33.7 32.7 31.7 30.7 29.7 28.7 27.7 26.7 25.7 24.7 23.7
 22.7 21.7 20.7 19.7 18.7 17.7 16.7 15.7 14.7 13.7 12.7 11.7 10.7  9.7
  8.7  7.7  6.7  5.7  4.7  3.7  2.7  1.7  0.7  0.3  1.3  2.3  3.3  4.3
  5.3  6.3  7.3  8.3  9.3 10.3 11.3 12.3 13.3 14.3 15.3 16.3 17.3 18.3
 19.3 20.3 21.3 22.3 23.3 24.3 25.3 26.3 27.3 28.3 29.3 30.3 31.3 32.3
 33.3 34.3 35.3 36.3 37.3 38.3 39.3 40.3 41.3 42.3 43.3 44.3 45.3 46.3
 47.3 48.3 49.3 50.3 51.3 52.3 53.3 54.3 55.3 56.3 57.3 58.3 59.3 60.3
 61.3 62.3]

最近值索引： 37
最近值： 37
